import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CookiesProvider } from "next-client-cookies/server";

import { Navbar } from "@/components/organisms";
import { TanstackQueryProvider, ThemeProvider } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <CookiesProvider>
            <TanstackQueryProvider>
              {/* TODO: Validate navbar logic */}
              <Navbar />
              <main>{children}</main>
              <Toaster />
            </TanstackQueryProvider>
          </CookiesProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
